<?php

namespace Dlabs\LaravelTrustedIp;


use Illuminate\Support\ServiceProvider;

class TrustedIpAddressProvider extends ServiceProvider
{


    public function boot()
    {
        $this->loadMigrationsFrom(__DIR__.'/migrations');
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
